title: Student Sustainability Workshop
author:
  name: Vangelis Raúl Velázquez González
  email: hello@vange.li
description: > # this means to ignore newlines until "show_excerpts:"
  The Student Sustainability Workshop is a unique, peer-to-peer educational
  program where students learn about important environmental issues and the
  ways that they can incorporate sustainable practices into their everyday
  lives, improve their quality of life, and save resources while saving money.
  Student also learn about careers in the emerging green economy and the paths
  they can take to pursue them.

show_excerpts: false # set to true to show excerpts on the homepage

minima:
  skin: solarized 
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: sustainablework
    instagram: sustainablework

header_pages:
  - about.md
  - hw.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
